### ISSUE TITLE
Can not connect Mysql Database

### ISSUE THREAD

**Issue by phuc1012000** [TanayB11/sql-injection-demo#4]
In the file dbconfig/db.js, password is passed as  process.env.MYSQL_CREDS.
But for some reasons can not be read correctly, and as a result yield ACCESS_ERR.
I have to change process.env.MYSQL_CREDS to my password directly.

**Comment by TanayB11** [comment]
When running the server, you need to set the environment variable in a file `.env` at the root of the project. If you haven't, try running the following shell command in the root of the project.

`echo 'MYSQL_CREDS="mysql_password"' > .env`.

If you've done that already, I suspect that you might need to install [dotenv](https://www.npmjs.com/package/dotenv) as a dependency and configure the environment variable that way.

**Comment by phuc1012000** [comment]
I have done echo 'MYSQL_CREDS="mysql_password"' > .env.
And still not work, dotenv seem to be a good solution.
But I have another question regard to security.
We have to store root password in raw form somehow? This definitely leads to some security problems. How can I hash my password and Express can still connect to mysql database?

**Comment by TanayB11** [comment]
I haven't looked into that, but this shouldn't be a security issue because the server code lives exclusively on the server, never on the client.

**Comment by phuc1012000** [comment]
The problem in the future when your product expands other developer with limited right will have access to root password of database, which only you, the owner of the product should have exclusive control.

I will mark this problem as solved
